### ISSUE TITLE
Component do calendário

### ISSUE THREAD

**Issue by GLCChaves** [gamaacademy/gama-avanade-tryout02#1]
Sei que já estamos avançados no quesito tempo, mas segue uma dúvida:
A intenção é que criemos o component do calendário desde o principio, ou devemos utilizar algum component já disponibilizado na web?
Pergunto isso pq acredito que utilizar um component pronto otimizaria um tanto quanto o tempo de execução.

**Comment by matheusrod92** [comment]
Boa noite @GLCChaves, a intenção do tryout é que ele seja resolvido e ponto.
Na minha opinião criar um component de Calendário ficaria mais fácil visto que você tem uma manipulação melhor/facil de todo o código! Mas se você preferir utilizar um framework fique à vontade desde que o comportamento de calendário com appointments esteja correto!
